[package]
name = "pysqlx-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pysqlx_core"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
python-source = "pysqlx_core"

[dependencies]
anyhow = "1.0.26"
bigdecimal = "0.2.2"
indexmap = { version = "1.7", features = ["serde-1"] }
indoc = "1.0.3"
once_cell = "1.15.0"
pyo3 = { version = "0.17.1", features = ["extension-module"] }
regex = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1"
tracing-error = "0.2"
tracing-futures = "0.2"
uuid = { version = "0.8.2", features = ["serde"] }
#pyo3-asyncio = "0.16.0"

[features]
vendored-openssl = ["quaint/vendored-openssl"]

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "postgresql",
    "mysql",
    "mssql",
    "sqlite",
    "json",
    "uuid",
    "chrono",
    "bigdecimal"
]