[package]
name = "pysqlx-core"
version = "0.1.7-beta"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = [
    "/pyproject.toml",
    "/LICENSE",
    "/README.md",
    "/convert",
    "/database",
    "/py_types",
    "/pysqlx_core.pyi",
    "/src"
]

[lib]
name = "pysqlx_core"
crate-type = ["rlib", "cdylib"]


[package.metadata.maturin]
python-source = "pysqlx_core"

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
pyo3-asyncio = { version = "0.17", features = ["tokio-runtime"] }

# my packages
py_types = { path = "py_types"}
convert = { path = "convert"}
database = { path = "database"}