name: ci2

on:
  pull_request:
    branches:
      - "main"
      - "deps/*"

    paths-ignore:
      - "LICENSE"
      - "SECURITY.md"
      - "makefile"
      - ".gitingore"
      #- ".github/workflows/*"
  push:
    branches:
      - "main"
      - "release/*"
      - "deps/*"
    paths-ignore:
      - "LICENSE"
      - "SECURITY.md"
      - "makefile"
      - ".gitingore"
      #- ".github/workflows/*"
  
env:
  PKG_CONFIG_ALLOW_CROSS: 1
  PY_SQLX_VERSION: 0.0.1 # change when the run "release - check package version"
  BEFORE_SCRIPT_LINUX: "cat etc/*release"

jobs:
  rust-test:
    # ignore because the pyo3 test not working
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set BEFORE_SCRIPT_LINUX from build.sh
        run: |
          echo "BEFORE_SCRIPT_LINUX=$(cat .github/build.sh)" >> $GITHUB_ENV


      - name: build wheel
        uses: PyO3/maturin-action@v1
        with:
          target: i686
          manylinux: auto
          args: >
            --release
            --out dist
            --interpreter '3.8 3.9 3.10 3.11 3.12 3.13 pypy3.9 pypy3.10'
          rust-toolchain: stable
          before-script-linux: ${{ env.BEFORE_SCRIPT_LINUX }}
          # sccache is not supported on Windows
          sccache: true
          docker-options: -e CI